In [ ]:
"""
KNN은 KMeans와 같이 K를 사용자가 직접 정해주어야 한다.
여러 K값으로 테스트해보고 가장 적당한 K를 정하게 된다. = K-인접 이웃 알고리즘
모든 계산이 이루어진 이후 분류를 수행하기 때문에 사례기반학습, 메모리기반학습 이라고도 한다.
Target 값이 있어야 되기 때문에 지도학습에 속한다.
학습 데이터가 많지 않아도 모델 성능이 괜찮은 장점이 있다.

어떤 데이터의 속성값을 예측할 때 주변에 인접한 값들의 속성값들을 비교해서 속성값을 정하는 알고리즘이다.
KNeighborsClassifier() : 범주형 데이터를 기반으로 예측할 때 사용
KNeighborsRegressor() : 연속형 값 예측
"""

In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

#데이터를 읽어오기
like = pd.read_csv('like.csv')
like.columns = ['talk' , 'book' , 'travel' , 'school' , 'tall' , 'skin' , 'muscle' , 'like_level']
like.head() # 데이터 5개 행만 출력

talk  book  travel  school  tall  skin  muscle like_level
0    30    80      40      40    90    90      50        1타입
1    60    50      70      50    60    60      90        2타입
2    50    40      80      60    50    70      80        2타입
3    90    50      60      30    40    20      30        3타입
4    50    70      30      70    70    80      60        1타입

In [8]:
#입력과 target데이터를 분리한다. 
x = np.array(like.drop('like_level', axis=1))
print(x.shape)
y = np.array(like.like_level)
print(y.shape)

(14, 7)
(14,)


In [9]:
y.shape , x.shape

((14,), (14, 7))

In [10]:
#데이터를 정규화한다. #사실 여기서 사용한 데이터 같은 경우 정규화를 해줄 필요가 없을 정도로 0~100 사이로 잘 분포 되어있다
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(x)

print(x)
x = scaler.transform(x)
x

StandardScaler()

In [100]:
#knn 분류기 모델을 만든다. 
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5)  
classifier.fit(x, y)  

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [101]:
#원래의 데이터를 넣어서 예측한다. 
y_pred = classifier.predict(x)  
y_pred

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [5]:
y

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [103]:
#모델을 평가한다. 
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y, y_pred))  
print(classification_report(y, y_pred))  

[[5 0 0]
 [0 4 0]
 [0 0 5]]
             precision    recall  f1-score   support

        1타입       1.00      1.00      1.00         5
        2타입       1.00      1.00      1.00         4
        3타입       1.00      1.00      1.00         5

avg / total       1.00      1.00      1.00        14

